# config/packages/routing.yaml
framework:
    router:
        utf8: true

        # Configure how to handle helper shopping URLs
        # strict_requirements: true

when@prod:
    framework:
        router:
            strict_requirements: null
